[package]
name = "AURA"
description = "Lua-based sound overhaul mod for Morrowind."
homepage = "https://www.nexusmods.com/morrowind/mods/48255"
repository = "https://github.com/tewlwolow/AURA"
authors = ["tewlwolow", "stanliqubit"]
version = "5.4.1"

[tools.mwse]
lua-mod = "tew.AURA"
wait-until-initialize = false

[dependencies]
assets = [
	"Textures\\tew\\AURA",
	"Sound\\tew\\A",
	"Sound\\Vo\\tew\\A",
	"Music\\tew\\AURA"
]

[dependencies.mwse]
buildnumber = 3150

[dependencies.mge-xe]
version = ">=0.15.0"
